### ISSUE TITLE
Add pause option.

### ISSUE THREAD

**Issue by krtkush** [krtkush/LinearTimer#1]
Give a method to pause and resume timer animation.

**Comment by krtkush** [comment]
This functionality has been added in #21 by @dakshsrivastava. After extensive testing and accepting the pull request, this issue will be closed.

**Comment by ArcherN9** [comment]
Never realised this was an issue under `enhancement` for this project. 😆 .

**Comment by krtkush** [comment]
#21 Has been merged with this issue branch. On testing, this feature seems to be working as intended. Also, we have "reset" action available too.

Thank you, @dakshsrivastava for working on this.
