### ISSUE TITLE
Timer won't resume

### ISSUE THREAD

**Issue by apexJCL** [krtkush/LinearTimer#24]
Scenario:

A previously paused LinearTimer won't resume it's execution nor its animation.

Current environment:

+ Smartphone with Android 6.0.1 (Moto X Play)
+ Android SDK Tools (up to date)
+ Min SDK: KitKat
+ LinearTimer version: 2.1.0

What I already tried:

Create a new project from scratch, setup LT library on gradle, create basic layout with view and buttons, start/pause works but resume won't.

**Comment by apexJCL** [comment]
Forgot to mention:

Play Store demo app works alright.

**Comment by krtkush** [comment]
This is a valid bug. Thank you for pointing it out, @apexJCL. 
I'll fix it ASAP and ship it in the next version. 

For the time being, as a workaround, you can implement the [Timer Listener](https://github.com/krtkush/LinearTimer/wiki/Usage#timer-listener)  and make sure you add the `getCountUpdate()` method when you initialize LinearTimer.

The following code for initializing should work -

```
linearTimer = new LinearTimer.Builder()
                .linearTimerView(linearTimerView)
                .duration(duration)
                .timerListener(this)
                .getCountUpdate(LinearTimer.COUNT_UP_TIMER, 1000)
                .build();
```
