### ISSUE TITLE
How to add text in middle of the circle?

### ISSUE THREAD

**Issue by YogeshLegendkiller** [krtkush/LinearTimer#33]
First i must say this library is awesome My Doubt is how to add text in the center of the circle ?

**Comment by krtkush** [comment]
Thank you.

The Library doesn't have an inbuilt textview for that. You'll have to add your own.
You can implement [Timer Listener](https://github.com/krtkush/LinearTimer/wiki/Usage#timer-listener) to update your TextView accordingly.
